"""Golden snapshots pinning the scoring prompt and the `record_score` schema.

`prompts.py` and `models.py` build their dimension lists from `dimensions.yaml`
instead of hardcoding them. That refactor must be a no-op on the wire: the same
system prompt bytes and the same tool schema go to Claude as before, because
both move eval scores.

The two constants below were captured from the pre-refactor code and are
deliberately written out longhand rather than derived from `DIMENSIONS`. A
snapshot generated by the code it is checking proves nothing.

If you intentionally add, remove, or reword a dimension, these tests will fail —
that is the point. Update the goldens in the same commit and rerun the evals.
"""

from pydantic import BaseModel

from src.dimensions import DIMENSIONS
from src.models import DimensionScore, ScoredCandidate, ScoreReport
from src.prompts import SCORING_SYSTEM_PROMPT

# Copied verbatim from src/prompts.py before the dimension block became dynamic.
GOLDEN_SCORING_SYSTEM_PROMPT = """You are a hiring evaluator matching candidates to \
a job description.

You will be given (1) the job description and (2) a structured candidate \
profile. Score the candidate by calling the `record_score` tool exactly once.

Score each dimension from 0 to 100:
- `skills_match`: overlap between the candidate's skills and the JD's \
required/nice-to-have skills.
- `experience_match`: does the candidate's years of experience and seniority \
align with the JD?
- `role_relevance`: how closely do the candidate's past roles resemble the \
role in the JD (domain, responsibilities, scope)?
- `overall_fit`: your holistic judgment — not a simple average of the above.

For each dimension, give one concise sentence of reasoning. Be specific \
(reference actual skills or roles), not generic.

`reasoning` is a two-sentence overall summary of why this candidate would or \
wouldn't work for this role.

`gaps` lists concrete, actionable gaps — a specific missing skill or a \
shortfall in years of experience. Do not list stylistic or subjective gaps. \
An empty list is fine if the candidate is a strong match.
"""

# Captured from ScoreReport.model_json_schema() before the refactor. This is the
# exact dict scorer.py hands to the API as the `record_score` input_schema.
GOLDEN_SCORE_REPORT_SCHEMA = {
    "$defs": {
        "DimensionScore": {
            "properties": {
                "score": {
                    "maximum": 100,
                    "minimum": 0,
                    "title": "Score",
                    "type": "integer",
                },
                "reasoning": {"title": "Reasoning", "type": "string"},
            },
            "required": ["score", "reasoning"],
            "title": "DimensionScore",
            "type": "object",
        },
        "Gap": {
            "properties": {
                "category": {
                    "enum": ["skill", "experience", "other"],
                    "title": "Category",
                    "type": "string",
                },
                "detail": {"title": "Detail", "type": "string"},
            },
            "required": ["category", "detail"],
            "title": "Gap",
            "type": "object",
        },
    },
    "description": (
        "What the scorer LLM returns. The orchestrator wraps this into a "
        "ScoredCandidate."
    ),
    "properties": {
        "skills_match": {"$ref": "#/$defs/DimensionScore"},
        "experience_match": {"$ref": "#/$defs/DimensionScore"},
        "role_relevance": {"$ref": "#/$defs/DimensionScore"},
        "overall_fit": {"$ref": "#/$defs/DimensionScore"},
        "reasoning": {
            "description": "Two-sentence overall reasoning for the scores.",
            "title": "Reasoning",
            "type": "string",
        },
        "gaps": {"items": {"$ref": "#/$defs/Gap"}, "title": "Gaps", "type": "array"},
    },
    "required": [
        "skills_match",
        "experience_match",
        "role_relevance",
        "overall_fit",
        "reasoning",
        "gaps",
    ],
    "title": "ScoreReport",
    "type": "object",
}

GOLDEN_DIMENSION_KEYS = [
    "skills_match",
    "experience_match",
    "role_relevance",
    "overall_fit",
]


# --- The two golden snapshots -------------------------------------------------


def test_scoring_system_prompt_is_unchanged_byte_for_byte() -> None:
    assert SCORING_SYSTEM_PROMPT == GOLDEN_SCORING_SYSTEM_PROMPT


def test_score_report_schema_is_unchanged() -> None:
    assert ScoreReport.model_json_schema() == GOLDEN_SCORE_REPORT_SCHEMA


# --- Field names on both models ----------------------------------------------


def test_score_report_exposes_exactly_the_expected_fields() -> None:
    assert list(ScoreReport.model_fields) == GOLDEN_DIMENSION_KEYS + [
        "reasoning",
        "gaps",
    ]


def test_scored_candidate_exposes_exactly_the_expected_fields() -> None:
    assert set(ScoredCandidate.model_fields) == set(GOLDEN_DIMENSION_KEYS) | {
        "profile",
        "reasoning",
        "gaps",
        "source_file",
    }


def test_scored_candidate_keeps_the_dimensions_in_config_order() -> None:
    present = [f for f in ScoredCandidate.model_fields if f in set(GOLDEN_DIMENSION_KEYS)]
    assert present == GOLDEN_DIMENSION_KEYS


def test_every_dimension_field_is_a_dimension_score() -> None:
    for key in GOLDEN_DIMENSION_KEYS:
        for model in (ScoreReport, ScoredCandidate):
            annotation = model.model_fields[key].annotation
            assert annotation is DimensionScore, f"{model.__name__}.{key} is {annotation}"


def test_every_dimension_field_is_required() -> None:
    for key in GOLDEN_DIMENSION_KEYS:
        for model in (ScoreReport, ScoredCandidate):
            assert model.model_fields[key].is_required(), f"{model.__name__}.{key}"


# --- The wiring itself --------------------------------------------------------


def test_models_and_prompt_are_driven_by_the_same_config() -> None:
    # The goldens above are hand-written; this one catches a dimensions.yaml
    # edit that lands in the prompt but not the schema, or vice versa.
    keys = [d.key for d in DIMENSIONS]
    assert keys == GOLDEN_DIMENSION_KEYS
    assert [f for f in ScoreReport.model_fields if f in set(keys)] == keys
    for dimension in DIMENSIONS:
        assert f"- `{dimension.key}`: " in SCORING_SYSTEM_PROMPT


def test_prompt_lists_the_dimensions_in_config_order() -> None:
    positions = [SCORING_SYSTEM_PROMPT.index(f"- `{d.key}`: ") for d in DIMENSIONS]
    assert positions == sorted(positions)


def test_prompt_describes_each_dimension_with_its_configured_sentence() -> None:
    # The bullet is rendered, not hardcoded, so the sentence must survive the
    # YAML round-trip (folded scalars, the em dash in overall_fit) intact. Each
    # bullet is one unwrapped line in the prompt value, so this is exact.
    bullets = [
        line for line in SCORING_SYSTEM_PROMPT.splitlines() if line.startswith("- `")
    ]

    assert bullets == [
        f"- `{d.key}`: {d.prompt_description}" for d in DIMENSIONS
    ]


def test_prompt_keeps_its_static_scaffolding() -> None:
    for fragment in (
        "You are a hiring evaluator matching candidates to a job description.",
        "Score each dimension from 0 to 100:",
        "For each dimension, give one concise sentence of reasoning. Be specific",
        "`reasoning` is a two-sentence overall summary",
        "`gaps` lists concrete, actionable gaps",
    ):
        assert fragment in SCORING_SYSTEM_PROMPT, fragment


def test_score_report_is_still_a_pydantic_model() -> None:
    # create_model() with the wrong base would still expose model_fields but
    # break validation everywhere downstream.
    assert issubclass(ScoreReport, BaseModel)
    assert issubclass(ScoredCandidate, BaseModel)


def test_score_report_still_validates_a_full_payload() -> None:
    payload = {
        **{k: {"score": 80, "reasoning": f"{k} reason"} for k in GOLDEN_DIMENSION_KEYS},
        "reasoning": "Two sentences. Really.",
        "gaps": [{"category": "skill", "detail": "No Kafka"}],
    }

    report = ScoreReport.model_validate(payload)

    assert report.skills_match.score == 80
    assert report.overall_fit.reasoning == "overall_fit reason"
    assert list(report.model_dump()) == list(ScoreReport.model_fields)
